'use client';
import { useRef, type FormEvent } from 'react';
import { directions, type Profile } from '../lib/admissions';
import { useLanguage } from './language';

const steps = ['О тебе','Учёба и интересы','Язык и экзамены','Страна обучения','Бюджет','Цели и готовность'];
const destinations = ['Германия','Польша','Нидерланды','США','Италия','Южная Корея','Казахстан'];
const subjects = ['Математика','Информатика','Английский','Физика','Биология','Искусство','Экономика'];
const priorities = [['scholarship','Стипендия'],['ranking','Репутация вуза'],['cost','Стоимость'],['location','Место обучения'],['career','Карьерные возможности']] as const;

export function AdmissionWizard({profile,step,setStep,patch,finish,back}:{profile:Profile;step:number;setStep:(value:number)=>void;patch:<K extends keyof Profile>(key:K,value:Profile[K])=>void;finish:()=>void;back:()=>void}){
 const {t}=useLanguage();
 const panel=useRef<HTMLFormElement>(null);
 const move=(next:number)=>{setStep(next);requestAnimationFrame(()=>panel.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'}))};
 const toggle=(key:'subjects'|'countries'|'alternatives',value:string,max:number)=>{const current=profile[key] ?? [];patch(key,current.includes(value)?current.filter(x=>x!==value):current.length<max?[...current,value]:current)};
 const choice=(value:string,active:boolean,onClick:()=>void)=> <button key={value} type="button" className={`wizard-chip ${active?'is-active':''}`} aria-pressed={active} onClick={onClick}>{t(value)}<span aria-hidden="true">{active?'✓':'+'}</span></button>;
 const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(step<5)move(step+1);else finish()};
 return <section className="workspace container wizard-page"><div className="workspace-top"><button className="back-button" onClick={back}>← {t('На главную')}</button><span className="local-note">{t('Сохраняется на этом устройстве')}</span></div>
 <div className="wizard-shell"><aside className="wizard-aside"><div className="eyebrow">{t('ТВОЙ МАРШРУТ')}</div><h1>{t('Сначала узнаем')}<br/><em>{t('тебя поближе.')}</em></h1><p>{t('Шесть коротких шагов — и у тебя будет понятный план поступления.')}</p><ol className="wizard-steps">{steps.map((name,i)=><li key={name} className={step===i?'current':step>i?'finished':''}><span>{step>i?'✓':`0${i+1}`}</span>{t(name)}</li>)}</ol><div className="wizard-aside-note"><span aria-hidden="true">✳</span>{t('Ответы остаются в твоём браузере. Их можно изменить позже.')}</div></aside>
 <form ref={panel} className="form-panel wizard-panel" onSubmit={submit}><div className="form-progress"><span>{t('ШАГ')} {step+1} / 6</span><span>{Math.round((step+1)/6*100)}%</span></div><div className="wizard-progress-track"><i style={{width:`${(step+1)/6*100}%`}}/></div>
 <div key={step} className="wizard-content">
 {step===0&&<><div className="wizard-kicker">01 / {t('О тебе')}</div><h2>{t('Где начинается твой путь?')}</h2><p className="wizard-intro">{t('Поймём, на каком ты этапе и когда планируешь поступать.')}</p><div className="wizard-fields two"><label className="field">{t('Возраст')}<input type="number" min="14" max="21" required value={profile.age || ''} onChange={e=>patch('age',Number(e.target.value))}/></label><label className="field">{t('Класс / год обучения')}<select value={profile.grade} onChange={e=>patch('grade',e.target.value)}>{['10 класс','11 класс','Выпускник'].map(x=><option key={x} value={x}>{t(x)}</option>)}</select></label></div><div className="wizard-fields two"><label className="field">{t('Страна проживания')}<select value={profile.residence} onChange={e=>patch('residence',e.target.value)}>{['Казахстан','Кыргызстан','Узбекистан','Таджикистан','Туркменистан','Другая страна'].map(x=><option key={x} value={x}>{t(x)}</option>)}</select></label><label className="field">{t('Год поступления')}<select value={profile.year} onChange={e=>patch('year',e.target.value)}>{['2027','2028','2029','2030'].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="wizard-fields two"><label className="field">{t('Гражданство')}<select value={profile.citizenship} onChange={e=>patch('citizenship',e.target.value)}>{['Казахстан','Другое'].map(x=><option key={x} value={x}>{t(x)}</option>)}</select></label><label className="field">{t('Школьный документ')}<select value={profile.schoolQualification} onChange={e=>patch('schoolQualification',e.target.value)}>{['Обычный аттестат','NIS Grade 12','IB Diploma','A-level','Другой'].map(x=><option key={x} value={x}>{t(x)}</option>)}</select></label></div><div className="wizard-callout"><b>{t('Твоя цель: зарубежный бакалавриат')}</b><span>{t('Этот маршрут создан для старшеклассников. Другие уровни образования пока не поддерживаются.')}</span></div></>}
 {step===1&&<><div className="wizard-kicker">02 / {t('Учёба и интересы')}</div><h2>{t('Что у тебя получается лучше всего?')}</h2><p className="wizard-intro">{t('Оценки помогают понять подготовку, а интересы — выбрать направление.')}</p><div className="wizard-fields two"><label className="field">{t('Система оценивания')}<select value={profile.gpaScale} onChange={e=>patch('gpaScale',Number(e.target.value))}>{[5,10,100].map(x=><option key={x} value={x}>{x}</option>)}</select></label><label className="field">{t('Средний балл')}<input type="number" required min="0" max={profile.gpaScale} step="0.01" value={profile.gpa} onChange={e=>patch('gpa',Number(e.target.value))}/></label></div><fieldset><legend>{t('Сильные предметы')} <small>{t('Выбери до трёх')}</small></legend><div className="wizard-chips">{subjects.map(x=>choice(x,profile.subjects.includes(x),()=>toggle('subjects',x,3)))}</div></fieldset><fieldset><legend>{t('Главное направление')}</legend><div className="wizard-direction-grid">{directions.map(x=>choice(x,profile.interest===x,()=>patch('interest',x)))}{choice('Своё направление',profile.interest==='Другое',()=>patch('interest','Другое'))}</div>{profile.interest==='Другое'&&<label className="field wizard-custom-field">{t('Напиши своё направление')}<input type="text" required pattern=".*\S.*" maxLength={60} value={profile.customInterest} onChange={e=>patch('customInterest',e.target.value)} placeholder={t('Например, биоинформатика')}/><small>{t('Покажем подтверждённые программы, если найдём подходящее направление.')}</small></label>}</fieldset><fieldset><legend>{t('Запасные направления')} <small>{t('Необязательно, до двух')}</small></legend><div className="wizard-chips">{directions.filter(x=>x!==profile.interest).map(x=>choice(x,profile.alternatives.includes(x),()=>toggle('alternatives',x,2)))}</div></fieldset></>}
 {step===2&&<><div className="wizard-kicker">03 / {t('Язык и экзамены')}</div><h2>{t('Какие экзамены уже позади?')}</h2><p className="wizard-intro">{t('Если не сдавал — это нормально. Добавим подготовку в маршрут.')}</p><fieldset><legend>{t('Английский язык')}</legend><div className="wizard-chips">{['Не сдавал','IELTS','TOEFL'].map(x=>choice(x,profile.englishExam===x,()=>patch('englishExam',x)))}</div></fieldset>{profile.englishExam==='Не сдавал'&&<fieldset className="wizard-language-level"><legend>{t('Как ты оцениваешь свой английский?')}</legend><p className="wizard-field-hint">{t('Выбери примерный уровень. Это самооценка, а не результат экзамена.')}</p><div className="wizard-chips">{['Не знаю','A1','A2','B1','B2','C1','C2'].map(x=>choice(x,profile.englishLevel===x,()=>patch('englishLevel',x)))}</div></fieldset>}{profile.englishExam==='IELTS'&&<label className="field wizard-narrow">IELTS Overall<input type="number" min="0" max="9" step="0.5" required value={profile.english==='0'?'':profile.english} onChange={e=>patch('english',e.target.value)} placeholder="6.0"/></label>}{profile.englishExam==='TOEFL'&&<label className="field wizard-narrow">TOEFL iBT<input type="number" min="0" max="120" required value={profile.toefl || ''} onChange={e=>patch('toefl',Number(e.target.value))} placeholder="90"/></label>}<fieldset><legend>SAT</legend><div className="wizard-chips">{choice('Пока не сдавал',profile.sat===0,()=>patch('sat',0))}{choice('Есть результат',profile.sat>0,()=>patch('sat',1250))}</div></fieldset>{profile.sat>0&&<label className="field wizard-narrow">SAT Score<input type="number" min="400" max="1600" step="10" required value={profile.sat} onChange={e=>patch('sat',Number(e.target.value))}/></label>}<fieldset><legend>{t('Готов сдавать SAT, если потребуется?')}</legend><div className="wizard-chips">{['Да','Не знаю','Нет'].map(x=>choice(x,profile.satWilling===x,()=>patch('satWilling',x)))}</div></fieldset></>}
 {step===3&&<><div className="wizard-kicker">04 / {t('Страна обучения')}</div><h2>{t('Где ты видишь себя студентом?')}</h2><p className="wizard-intro">{t('Выбери до трёх стран или оставь выбор открытым.')}</p><div className="wizard-chips">{destinations.map(x=>choice(x,profile.countries.includes(x),()=>toggle('countries',x,3)))}</div><div className="wizard-callout"><b>{t('Что для тебя важно в стране и вузе?')}</b><span>{t('На следующем шаге ты сможешь расставить приоритеты. Каталог содержит проверенные программы из семи стран.')}</span></div></>}
 {step===4&&<><div className="wizard-kicker">05 / {t('Бюджет')}</div><h2>{t('Какой бюджет тебе подходит?')}</h2><p className="wizard-intro">{t('Укажи максимум на обучение за один год. Проживание считается отдельно.')}</p><label className="field">{t('Максимум за год')}<strong className="wizard-budget">{new Intl.NumberFormat('en-US').format(profile.budget)} €</strong><input type="range" min="1000" max="35000" step="500" value={profile.budget} onChange={e=>patch('budget',Number(e.target.value))}/><span className="range-labels"><span>1 000 €</span><span>35 000 €+</span></span></label><fieldset><legend>{t('Нужна финансовая помощь?')}</legend><div className="wizard-chips">{['Обязательно','Желательно','Нет'].map(x=>choice(x,profile.aid===x,()=>patch('aid',x)))}</div></fieldset></>}
 {step===5&&<><div className="wizard-kicker">06 / {t('Цели и готовность')}</div><h2>{t('Что для тебя важнее всего?')}</h2><p className="wizard-intro">{t('Задай приоритеты — они повлияют на порядок рекомендаций.')}</p><div className="priority-list">{priorities.map(([key,label])=><div className="priority-row" key={key}><span>{t(label)}</span><div role="group" aria-label={t(label)}>{[['0','Не важно'],['1','Важно'],['2','Очень важно']].map(([value,name])=><button type="button" key={value} className={profile.priorities[key]===Number(value)?'is-active':''} aria-pressed={profile.priorities[key]===Number(value)} onClick={()=>patch('priorities',{...profile.priorities,[key]:Number(value)})}>{t(name)}</button>)}</div></div>)}</div><fieldset><legend>{t('Когда готов начать подачу?')}</legend><div className="wizard-chips">{['Уже готов','В течение года','Изучаю варианты'].map(x=>choice(x,profile.readiness===x,()=>patch('readiness',x)))}</div></fieldset><div className="wizard-callout"><b>{t('Репутация и карьера пока не участвуют в подборе')}</b><span>{t('Репутация и карьерные перспективы пока не участвуют в расчёте. Страна, стоимость и подтверждённые требования влияют на порядок вариантов.')}</span></div><div className="wizard-callout"><b>{t('Всё можно изменить позже')}</b><span>{t('После анкеты увидишь объяснимый подбор, сравнение и первый шаг своего плана.')}</span></div></>}
 </div><div className="form-footer"><button className="text-button" type="button" onClick={()=>step?move(step-1):back()}>← {t('Назад')}</button><button className="button" type="submit">{step===5?t('Построить мой маршрут'):t('Продолжить')} <span aria-hidden="true">↗</span></button></div></form></div></section>
}
