'use client';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { LanguagePicker, useLanguage } from './language';
import { AdmissionWizard } from './admission-wizard';
import { AdmissionProfile, AnalysisLoading } from './admission-analysis';
import { ProgramMatches, ProgramComparison } from './program-matches';
import { AdmissionRoadmap, clearRoadmapCache } from './admission-roadmap';
import { defaults, directions, programs, recommend, type Profile } from '../lib/admissions';
import { parseAiDiagnosis, type AiDiagnosis } from '../lib/ai-diagnosis';

type View = 'home'|'profile'|'analyzing'|'diagnosis'|'results'|'compare'|'plan';
type Saved = {profile: Profile; selected: string; done: string[]; compared: string[]; hasProfile: boolean};
const STORE = 'dalee-v1';
function Arrow(){return <span aria-hidden="true">↗</span>}
function Logo(){return <span className="logo"><span className="logo-mark" aria-hidden="true"><i/><i/></span>Continue<span className="logo-dot">.</span></span>}
function Reveal({children,className='',direction='up'}:{children:ReactNode;className?:string;direction?:string}) {
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const el=ref.current;if(!el)return; if(matchMedia('(prefers-reduced-motion: reduce)').matches)return; const obs=new IntersectionObserver(([e])=>{if(e.isIntersecting){el.classList.add('visible');obs.unobserve(el)}},{threshold:.14});el.classList.add('will-reveal');obs.observe(el);return()=>obs.disconnect()},[]);
 return <div ref={ref} className={`reveal ${direction} ${className}`}>{children}</div>;
}
function Model({kind='cards'}:{kind?:'cards'|'calendar'}) {
 const {localize}=useLanguage();
 return localize(<div className={`model model-${kind}`} aria-hidden="true">{kind==='cards'?<>
  <div className="model-shadow"/><div className="model-plinth"/>
  <div className="paper paper-left model-piece"><span className="paper-symbol">〈 〉</span><i/><i/><i/><small>ТВОИ ИНТЕРЕСЫ</small></div>
  <div className="paper paper-right model-piece"><span className="paper-chart"><i/><i/><i/></span><i/><i/><i/><small>ТВОИ ВОЗМОЖНОСТИ</small></div>
  <div className="selection-frame model-piece"><div className="paper paper-main"><span className="paper-circle"/><i/><i/><i/><span className="paper-badge">Твой выбор <span>✓</span></span></div></div>
  <div className="ribbon model-piece"/><div className="stone stone-one model-piece"/><div className="stone stone-two model-piece"/><span className="model-caption">Из вариантов — в твой план</span>
 </>:<><div className="calendar-back model-piece"><div className="check-row">✓ <i/></div><div className="check-row">✓ <i/></div><div className="check-row">✓ <i/></div><div className="check-row muted">○ <i/></div></div><div className="calendar-body model-piece"><div className="rings"><i/><i/><i/><i/></div><div className="calendar-heading">ТВОЙ СЛЕДУЮЩИЙ ШАГ</div><div className="calendar-grid">{Array.from({length:28},(_,i)=><span key={i} className={[5,12,17,24].includes(i)?'marked':''}>{i+1}</span>)}</div><div className="calendar-note"><span/> В твоём темпе</div></div><div className="calendar-tag model-piece">Всё складывается.</div></>}</div>);
}
const faqs=[['А если я ещё не знаю, куда поступать?','Начни с интересов. Выбери направление, которое хочется исследовать, а страну оставь открытой. Позже все ответы можно изменить — подбор и план обновятся.'],['Что меняется, если изменить бюджет или цели?','Программы заново упорядочиваются по твоим ограничениям. Мы показываем, что подходит и что нужно подготовить. При выборе программы план учитывает бюджет, английский и год поступления.'],['Откуда берутся требования к поступлению?',`В каталоге ${programs.length} реальные программы. Стоимость и требования взяты с официальных страниц вузов; год тарифа и дата проверки указаны в карточке. Перед подачей перепроверь условия выбранного набора.`],['Где сохраняются мои ответы?','Только в браузере на этом устройстве. Регистрация не нужна. Ты можешь очистить сохранённые данные в личном плане. После очистки браузера или на другом устройстве они недоступны.']];
export default function Home(){
 const {localize,t,locale}=useLanguage();
 const [view,setView]=useState<View>('home'); const [analysisStage,setAnalysisStage]=useState(0); const [aiInsight,setAiInsight]=useState<AiDiagnosis|null>(null); const [insightLocale,setInsightLocale]=useState(''); const [profile,setProfile]=useState<Profile>(defaults);const [step,setStep]=useState(0);const [hasProfile,setHasProfile]=useState(false);const [selected,setSelected]=useState('');const [compared,setCompared]=useState<string[]>([]);const [done,setDone]=useState<string[]>([]);const [ready,setReady]=useState(false);const [notice,setNotice]=useState('');const [menu,setMenu]=useState(false);const [privacy,setPrivacy]=useState(false);
 const heading=useRef<HTMLDivElement>(null);
 // Restore device-local state after hydration; server output must remain deterministic.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{try{const raw=localStorage.getItem(STORE);if(raw){const s=JSON.parse(raw) as Saved; if(s.profile && typeof s.profile.budget==='number' && [...directions,'Другое'].includes(s.profile.interest)){const restored={...defaults,...s.profile,countries:s.profile.countries ?? [],alternatives:s.profile.alternatives ?? [],subjects:s.profile.subjects ?? [],priorities:{...defaults.priorities,...s.profile.priorities},englishExam:s.profile.englishExam ?? (s.profile.english && s.profile.english!=='0'?'IELTS':'Не сдавал')};setProfile(restored);setSelected(recommend(restored).some(p=>p.id===s.selected)?s.selected:'');setDone(Array.isArray(s.done)?s.done.filter(x=>typeof x==='string'):[]);setCompared(Array.isArray(s.compared)?s.compared.filter(id=>recommend(restored).some(p=>p.id===id)).slice(0,3):[]);setHasProfile(!!s.hasProfile)}}}catch{setNotice('Не удалось прочитать сохранённые ответы. Можно начать заново.')}setReady(true)},[]);
 // A storage failure is external feedback, not derived UI state.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(STORE,JSON.stringify({profile,selected,done,compared,hasProfile}))}catch{setNotice('Браузер не сохраняет данные. Текущий план доступен до закрытия страницы.')}},[profile,selected,done,compared,hasProfile,ready]);
 useEffect(()=>{const onHash=()=>{const hash=location.hash.slice(1);if(['home','profile','analyzing','diagnosis','results','compare','plan'].includes(hash))setView(hash as View)};window.addEventListener('hashchange',onHash);onHash();return()=>window.removeEventListener('hashchange',onHash)},[]);
 useEffect(()=>{
  if(view!=='analyzing'||!hasProfile)return;
  const controller=new AbortController();
  let phase=0;
  const timer=window.setInterval(()=>{phase=Math.min(phase+1,3);setAnalysisStage(phase)},700);
  const delay=new Promise<void>(resolve=>window.setTimeout(resolve,2100));
  const analysis=fetch('/api/diagnosis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile,locale}),signal:controller.signal})
   .then(async response=>{if(!response.ok)throw new Error('AI unavailable');const data=await response.json() as {insight?:unknown};return parseAiDiagnosis(data.insight)})
   .catch(()=>null);
  void Promise.all([analysis,delay]).then(([insight])=>{
   if(controller.signal.aborted)return;
   setAiInsight(insight);setInsightLocale(locale);setView('diagnosis');history.replaceState(null,'','#diagnosis');window.scrollTo({top:0,behavior:'instant'});
  });
  return()=>{controller.abort();window.clearInterval(timer)};
 },[view,hasProfile,profile,locale]);
 function go(next:View){setView(next);setMenu(false);history.pushState(null,'','#'+next);window.scrollTo({top:0,behavior:'instant'});requestAnimationFrame(()=>heading.current?.focus())}
 function begin(){setStep(0);setAiInsight(null);go('profile')}
 function example(){setProfile({...defaults,name:'Alex'});setHasProfile(true);setCompared(['constructor-cs','wut-cs']);setSelected('');setDone([]);go('results')}
 function patch<K extends keyof Profile>(key:K,value:Profile[K]){setProfile(p=>({...p,[key]:value}));setAiInsight(null);if(['interest','customInterest','countries','country','citizenship','schoolQualification'].includes(key)){setSelected('');setCompared([])}}
 const ranked=recommend(profile);const chosen=ranked.find(p=>p.id===selected);
 function pick(id:string){setSelected(id);go('plan')}
 function toggleCompare(id:string){setCompared(c=>c.includes(id)?c.filter(x=>x!==id):c.length<3?[...c,id]:c)}
 const comparePrograms=ranked.filter(p=>compared.includes(p.id));
 function clear(){if(window.confirm(t('Удалить профиль и прогресс с этого устройства?'))){clearRoadmapCache();setProfile(defaults);setAiInsight(null);setSelected('');setCompared([]);setDone([]);setHasProfile(false);go('home')}}
 return localize(<><a className="skip-link" href="#main">К содержимому</a><header className="header"><div className="container nav"><button className="logo-button" onClick={()=>go('home')} aria-label="Далее — главная"><Logo/></button><nav className={menu?'nav-links open':'nav-links'} aria-label="Основная навигация">{view==='home'?<><a href="#how" onClick={()=>setMenu(false)}>Как это работает</a><button onClick={example}>Пример маршрута</button><a href="#faq" onClick={()=>setMenu(false)}>Вопросы</a></>:<><button className={view==='diagnosis'?'active':''} onClick={()=>go(hasProfile?'diagnosis':'profile')}>Диагностика</button><button className={view==='results'?'active':''} onClick={()=>go('results')}>Подбор</button><button className={view==='compare'?'active':''} onClick={()=>go('compare')}>Сравнение{compared.length>0&&<span className="nav-count">{compared.length}</span>}</button><button className={view==='plan'?'active':''} onClick={()=>go('plan')}>Мой план</button></>}</nav><div className="nav-actions"><LanguagePicker/><button className="text-button desktop" onClick={()=>hasProfile?go(selected?'plan':'results'):begin()}>{hasProfile?'Мой маршрут':'Мой профиль'}</button><button className="button small" onClick={begin}>{hasProfile?'Изменить профиль':'Начать'}<Arrow/></button><button className="menu-button" aria-label="Меню" aria-expanded={menu} onClick={()=>setMenu(!menu)}>☰</button></div></div></header>
 <main id="main" ref={heading} tabIndex={-1}>{notice&&<div className="notice container" role="status">{notice}</div>}
 {view==='home'?<>
 <section className="hero container"><Reveal direction="left" className="hero-copy"><div className="eyebrow"><span className="tiny-line"/> ПОСТУПЛЕНИЕ В ТВОЁМ ТЕМПЕ</div><h1>Куда поступать.<br/><em>С чего начать.</em></h1><p className="lead">Большие планы становятся ближе,<br className="desktop"/> когда понятен следующий шаг.</p><p className="hero-description">Найди программу под свои интересы и собери<br className="desktop"/> маршрут поступления — от выбора до заявки.</p><div className="hero-actions"><button className="button" onClick={begin}>Построить маршрут <Arrow/></button><button className="text-button" onClick={example}>Посмотреть пример <span>↗</span></button></div><div className="hero-footnote"><span className="small-check">✓</span> Без регистрации <span className="dot"/> Ответы можно изменить</div></Reveal><Reveal direction="right" className="hero-art"><Model/><span className="art-index">01 / ВЫБРАТЬ СВОЁ</span></Reveal></section>
 <div className="container principle-strip"><span>Твои интересы</span><i/><span>Твои возможности</span><i/><span>Твой следующий шаг</span><span className="strip-end">Всё складывается в маршрут <span>↘</span></span></div>
 <section id="how" className="section container"><Reveal><div className="section-top"><div><div className="eyebrow">НЕ ПРОСТО СПИСОК УНИВЕРСИТЕТОВ</div><h2>Много вариантов.<br/><em>Один — ближе тебе.</em></h2></div><p>Интересы, бюджет и планы на будущее.<br/>Поможем увидеть, что подходит тебе<br/>и что понадобится для поступления.</p></div></Reveal><Reveal className="showcase"><div className="showcase-art"><Model/><div className="sample-caption">Выбор начинается с тебя</div></div><div className="showcase-content"><span className="pill">ПРИМЕР ПОДБОРА</span><h3>Компьютерные науки</h3><p className="muted-text">Здесь твои интересы становятся направлением.</p><dl className="match-list"><div><dt><span>⌘</span> Интересы</dt><dd>Технологии и продукты</dd></div><div><dt><span>↔</span> Бюджет</dt><dd>В твоём диапазоне</dd></div><div><dt><span>↗</span> Следующий шаг</dt><dd>Сравнить программы</dd></div></dl><button className="text-button plum" onClick={example}>Посмотреть пример подбора <Arrow/></button><span className="demo-note">Иллюстрация интерфейса · подбор из реального каталога</span></div></Reveal></section>
 <section className="section container plan-section"><Reveal direction="left"><div className="eyebrow">ОТ ЦЕЛИ К ДЕЙСТВИЮ</div><h2>Большой путь.<br/><em>Посильные шаги.</em></h2><p className="section-description">Экзамены, документы и сроки — в одном плане.<br/>Не всё сразу. Только то, что важно сейчас.</p><div className="steps">{[['Расскажи о себе','Интересы, возможности и то, к чему стремишься.'],['Выбери подходящее','Сравни варианты и пойми причины подбора.'],['Двигайся в своём темпе','Начни с одной задачи. Отмечай свой прогресс.']].map(([title,desc],i)=><div className="step-row" key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{desc}</p></div></div>)}</div></Reveal><Reveal direction="right" className="calendar-art"><Model kind="calendar"/><span className="art-index">02 / СДЕЛАТЬ ПЕРВЫЙ ШАГ</span></Reveal></section>
 <section id="faq" className="section container faq-section"><Reveal><div className="eyebrow">ДАВАЙ РАЗБЕРЁМСЯ</div><h2>Есть вопросы?<br/><em>Это нормально.</em></h2><p className="section-description">Первый шаг не обязан быть очевидным.</p></Reveal><Reveal className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</Reveal></section>
 <section className="container cta-wrap"><Reveal className="cta"><div><span className="eyebrow">НАЧНИ С ТОГО, ЧТО ВАЖНО ТЕБЕ</span><h2>Твой следующий шаг — здесь.</h2><p>Твои цели. Твой темп. Твой план.</p></div><button className="button light" onClick={begin}>Составить мой план <Arrow/></button><span className="cta-decoration" aria-hidden="true">↗</span></Reveal></section>
 </>:view==='profile'?<AdmissionWizard profile={profile} step={step} setStep={setStep} patch={patch} finish={()=>{setHasProfile(true);setAnalysisStage(0);go('analyzing')}} back={()=>go(hasProfile?'diagnosis':'home')}/>:view==='analyzing'&&hasProfile?<AnalysisLoading stage={analysisStage}/>:view==='diagnosis'&&hasProfile?<AdmissionProfile profile={profile} insight={insightLocale===locale?aiInsight:null} onMatches={()=>go('results')} onEdit={begin}/>:!hasProfile?<section className="empty-state container"><div className="eyebrow">НАЧНЁМ СО ЗНАКОМСТВА</div><h1>Маршрут начинается<br/><em>с твоих целей.</em></h1><p>Ответь на несколько вопросов, чтобы увидеть подбор и план.</p><button className="button" onClick={begin}>Заполнить профиль <Arrow/></button></section>:view==='results'?<ProgramMatches profile={profile} ranked={ranked} compared={compared} onEdit={begin} onPick={pick} onCompare={toggleCompare} onComparePage={()=>go('compare')}/>:view==='compare'?<ProgramComparison profile={profile} items={comparePrograms} onBack={()=>go('results')} onPick={pick} onRemove={toggleCompare}/>:chosen?<AdmissionRoadmap profile={profile} program={chosen} done={done} onToggle={id=>setDone(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id])} onBack={()=>go('results')} onEdit={begin} onClear={clear}/>:<section className="workspace container"><div className="workspace-top"><button className="back-button" onClick={()=>go('results')}>← К программам</button></div><div className="empty-state"><h1>Выбери цель.<br/><em>Соберём маршрут.</em></h1><p>Выбери программу из подбора, чтобы увидеть персональные задачи.</p><button className="button" onClick={()=>go('results')}>К программам <Arrow/></button></div></section>}
 </main><footer className="footer container"><button className="logo-button" onClick={()=>go('home')}><Logo/></button><span>Большие планы. Понятные шаги.</span><button onClick={()=>setPrivacy(!privacy)}>О данных и проекте</button><small>LOCUS · Кейс 02 · Прототип</small></footer>{privacy&&<div className="privacy-panel container" role="region" aria-label="О данных и проекте"><h2>Твои данные — на твоём устройстве</h2><p>«Далее» — прототип для LOCUS Startup Hackathon 2026. Ключевые ограничения определяются прозрачными правилами; после анкеты текстовые рекомендации может подготовить AI-модель Groq. Каталог содержит 22 реальные программы с официальными источниками и датами проверки; неполные данные отмечены. Ответы и отметки хранятся локально в браузере. Для AI-диагностики, сравнения и маршрута ответы анкеты передаются Groq; сервис не отправляет заявки и не гарантирует поступление.</p><button className="text-button" onClick={()=>setPrivacy(false)}>Закрыть ×</button></div>}</>);
}
