'use client';
import { useEffect, useState } from 'react';
import { type Profile } from '../lib/admissions';
import { comparisonFacts, comparisonWinner, fallbackComparison, parseComparisonNarrative, type ComparisonNarrative } from '../lib/comparison-analysis';
import { type Program } from '../lib/program-catalog';
import { useLanguage } from './language';

type Item=Program & {reasons:string[];gaps:string[];score:number};
type Props={profile:Profile;items:Item[];onBack:()=>void;onPick:(id:string)=>void;onRemove:(id:string)=>void};
const copy={
 ru:{eyebrow:'02 / УМНОЕ СРАВНЕНИЕ',title:'Сравним по делу.',sub:'Смотрим, как каждый вариант соотносится с твоим бюджетом, английским и условиями поступления.',loading:'Сопоставляем программы',loadingSub:'Проверяем подтверждённые данные и готовим объяснимый вывод.',phases:['Сверяем стоимость и бюджет','Проверяем язык и путь поступления','Ищем компромиссы','Формулируем вердикт'],back:'← К подбору',empty:'Выбери хотя бы две программы',emptySub:'На карточках в подборе нажми «Сравнить».',return:'Вернуться к программам ↗',rerun:'Обновить анализ ↗',ai:'Анализ Groq AI',fallback:'Анализ по данным каталога',overview:'ОБЩАЯ КАРТИНА',programs:'Каждая программа — подробно',strengths:'Что играет в плюс',risks:'Что требует внимания',step:'Ближайшее действие',budget:'Бюджет',language:'Английский',pathway:'Поступление',deadline:'Срок подачи',inBudget:'В пределах бюджета',overBudget:'Выше бюджета',unknown:'Нужно уточнить',languageMet:'Общий IELTS достигает порога',languageBelow:'Общий IELTS ниже порога',languageMissing:'Экзамен не сдан',languageUnknown:'Требования нужно сверить',pathwayBlocked:'Прямой путь ограничен',pathwayCheck:'Требуется проверка',dateKnown:'Подтверждён',dateUnknown:'Не подтверждён',winner:'ВЕРДИКТ ДЛЯ ТВОЕГО ПРОФИЛЯ',preferred:'Ближе к твоим условиям',tradeoff:'Главный компромисс',first:'С чего начать',choose:'Построить план ↗',remove:'Убрать',facts:'Официальные источники',programSource:'Программа ↗',costSource:'Стоимость ↗',languageSource:'Язык ↗',method:'Как мы сравниваем',methodText:'Порядок вариантов рассчитывается по подтверждённым сигналам: стоимость относительно бюджета, общий IELTS, прямой путь поступления и срок. Groq AI объясняет эти данные и компромиссы. Это не оценка шанса поступления. Сборы, проживание и возможные гранты не входят в расчёт стоимости; непроверенные данные не считаются выполненными требованиями.'},
 en:{eyebrow:'02 / SMART COMPARISON',title:'Compare what matters.',sub:'See how each option fits your budget, English level, and admission requirements.',loading:'Comparing programs',loadingSub:'Checking verified facts and preparing an explainable recommendation.',phases:['Checking tuition against budget','Reviewing language and entry path','Finding tradeoffs','Preparing the verdict'],back:'← Back to matches',empty:'Choose at least two programs',emptySub:'Select “Compare” on program cards.',return:'Back to programs ↗',rerun:'Refresh analysis ↗',ai:'Groq AI analysis',fallback:'Catalog-based analysis',overview:'THE BIG PICTURE',programs:'Each program in detail',strengths:'What works in your favor',risks:'What needs attention',step:'Next action',budget:'Budget',language:'English',pathway:'Admission path',deadline:'Application deadline',inBudget:'Within budget',overBudget:'Above budget',unknown:'Needs checking',languageMet:'Overall IELTS meets threshold',languageBelow:'Overall IELTS below threshold',languageMissing:'No exam yet',languageUnknown:'Requirements need checking',pathwayBlocked:'Direct entry is restricted',pathwayCheck:'Needs verification',dateKnown:'Confirmed',dateUnknown:'Unconfirmed',winner:'VERDICT FOR YOUR PROFILE',preferred:'Closest to your needs',tradeoff:'Main tradeoff',first:'Where to start',choose:'Build my plan ↗',remove:'Remove',facts:'Official sources',programSource:'Program ↗',costSource:'Tuition ↗',languageSource:'English ↗',method:'How the comparison works',methodText:'Options are ordered using verified signals: tuition against budget, overall IELTS, direct entry, and deadlines. Groq AI explains these facts and tradeoffs. This is not an admission probability. Fees, living costs, and possible grants are excluded from tuition estimates; unverified data do not count as fulfilled requirements.'},
 kk:{eyebrow:'02 / АҚЫЛДЫ САЛЫСТЫРУ',title:'Маңыздысын салыстырайық.',sub:'Әр нұсқаның бюджетіңе, ағылшын деңгейіңе және қабылдау шарттарына сәйкестігін қара.',loading:'Бағдарламаларды салыстырып жатырмыз',loadingSub:'Расталған деректерді тексеріп, түсінікті қорытынды дайындап жатырмыз.',phases:['Оқу ақысы мен бюджетті салыстыру','Тіл мен қабылдау жолын тексеру','Ымыраларды анықтау','Қорытынды дайындау'],back:'← Іріктеуге қайту',empty:'Кемінде екі бағдарлама таңда',emptySub:'Бағдарлама карталарында «Салыстыру» түймесін бас.',return:'Бағдарламаларға қайту ↗',rerun:'Талдауды жаңарту ↗',ai:'Groq AI талдауы',fallback:'Каталог деректеріне негізделген талдау',overview:'ЖАЛПЫ КӨРІНІС',programs:'Әр бағдарлама егжей-тегжейлі',strengths:'Артықшылықтар',risks:'Назар аударатын тұстар',step:'Келесі әрекет',budget:'Бюджет',language:'Ағылшын тілі',pathway:'Қабылдау жолы',deadline:'Өтініш мерзімі',inBudget:'Бюджет шегінде',overBudget:'Бюджеттен жоғары',unknown:'Нақтылау керек',languageMet:'Жалпы IELTS шекке жетеді',languageBelow:'Жалпы IELTS шектен төмен',languageMissing:'Емтихан тапсырылмаған',languageUnknown:'Талаптарды нақтылау керек',pathwayBlocked:'Тікелей түсу шектелген',pathwayCheck:'Тексеру қажет',dateKnown:'Расталған',dateUnknown:'Расталмаған',winner:'СЕНІҢ БЕЙІНІҢЕ АРНАЛҒАН ҚОРЫТЫНДЫ',preferred:'Талаптарыңа жақынырақ',tradeoff:'Негізгі ымыра',first:'Неден бастау керек',choose:'Жоспар құру ↗',remove:'Алып тастау',facts:'Ресми дереккөздер',programSource:'Бағдарлама ↗',costSource:'Оқу ақысы ↗',languageSource:'Тіл ↗',method:'Салыстыру әдісі',methodText:'Нұсқалар расталған деректер бойынша реттеледі: оқу ақысы мен бюджет, жалпы IELTS, тікелей түсу жолы және мерзімдер. Groq AI осы деректер мен ымыраларды түсіндіреді. Бұл оқуға түсу ықтималдығы емес. Алымдар, тұру шығыны және ықтимал гранттар оқу ақысының есебіне кірмейді; тексерілмеген деректер орындалған талап болып саналмайды.'}
} as const;

export function ProgramComparison({profile,items,onBack,onPick,onRemove}:Props){
 const {locale}=useLanguage();const c=copy[locale];
 const [narrative,setNarrative]=useState<ComparisonNarrative|null>(null);
 const [source,setSource]=useState<'ai'|'fallback'>('fallback');
 const [loading,setLoading]=useState(false);const [stage,setStage]=useState(0);const [retry,setRetry]=useState(0);
 const ids=items.map(p=>p.id).join('|');
 const facts=comparisonFacts(profile,items);const winner=comparisonWinner(facts);
 useEffect(()=>{
  if(items.length<2||!winner)return;
  const controller=new AbortController();
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setNarrative(null);setLoading(true);setStage(0);
  const phase=window.setInterval(()=>setStage(s=>Math.min(s+1,3)),600);
  const delay=new Promise<void>(resolve=>window.setTimeout(resolve,1700));
  const analysis=fetch('/api/comparison',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile,ids:items.map(p=>p.id),locale}),signal:controller.signal})
   .then(async response=>{if(!response.ok)throw new Error('AI unavailable');const data=await response.json() as {insight?:unknown};return parseComparisonNarrative(data.insight,items.map(p=>p.id),winner.id)})
   .catch(()=>null);
  void Promise.all([analysis,delay]).then(([result])=>{if(controller.signal.aborted)return;setNarrative(result??fallbackComparison(facts,winner.id));setSource(result?'ai':'fallback');setLoading(false);window.scrollTo({top:0,behavior:'smooth'});});
  return()=>{controller.abort();window.clearInterval(phase)};
 // The selected IDs and profile revision define one analysis run.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[ids,profile,locale,retry]);
 if(items.length<2)return <section className="workspace container compare-page"><div className="workspace-top"><button className="back-button" onClick={onBack}>{c.back}</button><span className="eyebrow">{c.eyebrow}</span></div><div className="empty-state"><h1>{c.empty}</h1><p>{c.emptySub}</p><button className="button" onClick={onBack}>{c.return}</button></div></section>;
 if(loading||!narrative)return <section className="workspace container compare-page compare-loading" aria-live="polite"><div className="workspace-top"><button className="back-button" onClick={onBack}>{c.back}</button><span className="eyebrow">{c.eyebrow}</span></div><div className="compare-loading-body"><div className="compare-orbit" aria-hidden="true"><span/><span/><span/><b>↗</b></div><h1>{c.loading}<span className="compare-dots">...</span></h1><p>{c.loadingSub}</p><div className="compare-loading-cards" aria-hidden="true">{items.map((p,i)=><div key={p.id} style={{animationDelay:`${i*120}ms`}}><i/ ><span>{p.school}</span><small>{p.title}</small></div>)}</div><ol className="compare-phases">{c.phases.map((p,i)=><li key={p} className={i<stage?'done':i===stage?'active':''}><span>{i<stage?'✓':`0${i+1}`}</span>{p}</li>)}</ol></div></section>;
 const selected=facts.find(f=>f.id===narrative.verdict.winnerId)??winner!;
 return <section className="workspace container compare-page"><div className="workspace-top"><button className="back-button" onClick={onBack}>{c.back}</button><span className="eyebrow">{c.eyebrow}</span></div>
  <div className="compare-hero"><div><span className="compare-pill"><i/>{source==='ai'?c.ai:c.fallback}</span><h1>{c.title}</h1><p>{c.sub}</p></div><div className="compare-hero-mark" aria-hidden="true">↗<span>{items.length.toString().padStart(2,'0')} / 03</span></div></div>
  <div className="compare-overview"><span className="eyebrow">{c.overview}</span><p>{narrative.overview}</p><button className="text-button" onClick={()=>setRetry(n=>n+1)}>{c.rerun}</button></div>
  <div className="compare-heading"><span className="eyebrow">01 / {c.programs}</span><h2>{c.programs}</h2></div>
  <div className="compare-programs">{facts.map((f,i)=>{const story=narrative.programs.find(p=>p.id===f.id);return <article className={`compare-program ${f.id===selected.id?'is-preferred':''}`} key={f.id} style={{animationDelay:`${i*110}ms`}}><div className="compare-program-top"><span>{String(i+1).padStart(2,'0')} / {f.country}</span><button onClick={()=>onRemove(f.id)} aria-label={`${c.remove} ${f.school}`}>×</button></div><h3>{f.school}</h3><p className="compare-program-title">{f.title}</p>{f.id===selected.id&&<span className="compare-preferred">↗ {c.preferred}</span>}<p className="compare-fit">{story?.fit}</p><div className="compare-metrics"><div><span>{c.budget}</span><strong className={f.budget==='within'?'good':f.budget==='above'?'caution':''}>{f.budget==='within'?c.inBudget:f.budget==='above'?c.overBudget:c.unknown}</strong><small>{f.tuition}</small></div><div><span>{c.language}</span><strong className={f.language==='metOverall'?'good':f.language==='belowOverall'?'caution':''}>{f.language==='metOverall'?c.languageMet:f.language==='belowOverall'?c.languageBelow:f.language==='notTaken'?c.languageMissing:c.languageUnknown}</strong><small>{f.languageDetail}</small></div><div><span>{c.pathway}</span><strong className={f.pathway==='blockedDirect'?'caution':''}>{f.pathway==='blockedDirect'?c.pathwayBlocked:c.pathwayCheck}</strong></div><div><span>{c.deadline}</span><strong>{f.deadlineConfirmed?c.dateKnown:c.dateUnknown}</strong>{f.deadline&&<small>{f.deadline}</small>}</div></div><div className="compare-story"><div><h4>{c.strengths}</h4><ul>{story?.strengths.map(s=><li key={s}><span>✓</span>{s}</li>)}</ul></div><div><h4>{c.risks}</h4><ul>{story?.risks.map(s=><li key={s}><span>!</span>{s}</li>)}</ul></div></div><div className="compare-next"><span>{c.step}</span><p>{story?.nextStep}</p></div><details className="compare-sources"><summary>{c.facts}</summary><a href={f.source} target="_blank" rel="noopener noreferrer">{c.programSource}</a>{f.tuitionSource&&<a href={f.tuitionSource} target="_blank" rel="noopener noreferrer">{c.costSource}</a>}<a href={f.englishSource} target="_blank" rel="noopener noreferrer">{c.languageSource}</a></details></article>})}</div>
  <div className="compare-verdict"><div className="compare-verdict-main"><span>{c.winner}</span><h2>{selected.school}</h2><p className="compare-verdict-sub">{selected.title} · {selected.country}</p><p className="compare-verdict-why">{narrative.verdict.why}</p><button className="button light" onClick={()=>onPick(selected.id)}>{c.choose}</button></div><div className="compare-verdict-side"><div><span>01 / {c.tradeoff}</span><p>{narrative.verdict.tradeoff}</p></div><div><span>02 / {c.first}</span><p>{narrative.verdict.firstAction}</p></div></div></div>
  <details className="compare-method"><summary>{c.method}</summary><p>{c.methodText}</p></details>
 </section>;
}
