/** Official-source catalogue. Prices are for a Kazakhstan passport unless a row says otherwise. */
export type Currency = 'EUR' | 'USD' | 'PLN' | 'KRW' | 'KZT' | 'GBP' | 'CAD' | 'AUD' | 'JPY' | 'SGD';
export type Tuition = { amount: number; currency: Currency; period: 'year' | 'semester' | 'month' | 'credit'; year: string; source: string; note?: string; annualRange?: { min: number; max: number; credits: number } };
export type Deadline = { date: string; label: string; intake: string; source: string };
export type Program = {
 id: string; title: string; school: string; country: string; interest: string; duration: string; accent: 'plum'|'sand'|'sage'; coverImage?: string; verified?: boolean;
 programUrl: string; admissionUrl: string; costUrl?: string; checkedOn: string;
 tuition: Tuition | null; english: { ielts: number | null; detail: string; source: string };
 deadline: Deadline | null; admissionNote: string; scholarshipNote: string; specialRequirement?: string;
};

const checkedOn = '2026-09-18';
const twenteDiploma = 'Для прямого поступления с казахстанским школьным дипломом Twente указывает NIS Grade 12 с профильными предметами Higher Level. Обычный аттестат не признаётся эквивалентом VWO.';
const twenteAdmission = 'https://www.utwente.nl/en/education/bachelor/application-admission/admission/';
const twenteEnglish = 'https://www.utwente.nl/en/education/bachelor/application-admission/admission/language-requirements/';
const twenteFees = 'https://www.utwente.nl/en/education/bachelor/tuition-fees/';
const rhineFees = 'https://www.hochschule-rhein-waal.de/en/academics/students/costs-scholarships-and-grants/tuition-and-fees';
const yonseiFees = 'https://uic.yonsei.ac.kr/admission.php?mid=m04_03';
const yonseiAdmission = 'https://uic.yonsei.ac.kr/admission.php?mid=m04_02_02';

export const programs: Program[] = [
 {id:'constructor-cs',title:'Computer Science',school:'Constructor University',country:'Германия',interest:'Технологии',duration:'3 года',accent:'plum',programUrl:'https://constructor.university/programs/undergraduate-education/computer-science',admissionUrl:'https://constructor.university/programs/undergraduate-education/computer-science',checkedOn,tuition:{amount:11925,currency:'EUR',period:'semester',year:'2027/28',source:'https://constructor.university/programs/undergraduate-education/computer-science',note:'Разовый взнос для non-EU: €940; проживание и иные сборы отдельно.'},english:{ielts:null,detail:'Подтверди английский по актуальным правилам приёма; порог IELTS в проверенном источнике не зафиксирован.',source:'https://constructor.university/programs/undergraduate-education/faq-undergraduate-study'},deadline:{date:'2027-07-15',label:'Rolling admission',intake:'2027',source:'https://constructor.university/programs/undergraduate-education/computer-science'},admissionNote:'Early Action до 1 февраля 2027; затем rolling admission. Требуется документ о среднем образовании.',scholarshipNote:'Все поступившие рассматриваются на академическую стипендию; размер индивидуален.'},
 {id:'rhine-iba',title:'International Business Administration',school:'Rhine-Waal University of Applied Sciences',country:'Германия',interest:'Бизнес',duration:'7 семестров',accent:'sage',programUrl:'https://www.hochschule-rhein-waal.de/en/international-business-administration-ba',admissionUrl:'https://www.hochschule-rhein-waal.de/en/academics/prospective-students/guide-international-applicants',checkedOn,tuition:{amount:0,currency:'EUR',period:'year',year:'2026/27',source:rhineFees,note:'Обучение без tuition; обязательный взнос за зимний семестр 2026/27 — €365,10. Размер на 2027/28 пока не подтверждён.'},english:{ielts:null,detail:'Английский не ниже CEFR B2; допустимый сертификат уточнить у вуза.',source:'https://www.hochschule-rhein-waal.de/en/international-business-administration-ba'},deadline:null,admissionNote:'Иностранные школьные документы обычно подаются через uni-assist; программа с ограниченным приёмом.',specialRequirement:'8-недельную практику нужно завершить до четвёртого семестра.',scholarshipNote:'Стипендию и право на неё проверяй отдельно; подтверждённой гарантии финансирования нет.'},
 {id:'rhine-icd',title:'Information and Communication Design',school:'Rhine-Waal University of Applied Sciences',country:'Германия',interest:'Дизайн',duration:'7 семестров',accent:'sand',programUrl:'https://www.hochschule-rhein-waal.de/en/information-and-communication-design-ba',admissionUrl:'https://www.hochschule-rhein-waal.de/en/faculties/communication-and-environment/degree-programmes/bachelor-degree-programmes/information-0',checkedOn,tuition:{amount:0,currency:'EUR',period:'year',year:'2026/27',source:rhineFees,note:'Обучение без tuition; обязательный взнос за зимний семестр 2026/27 — €365,10.'},english:{ielts:null,detail:'Программа на английском; конкретный порог IELTS нужно проверить в правилах приёма.',source:'https://www.hochschule-rhein-waal.de/en/information-and-communication-design-ba'},deadline:null,admissionNote:'Заявка включает отдельную проверку творческих способностей и обычную подачу документов.',specialRequirement:'Портфолио и успешная portfolio assessment обязательны.',scholarshipNote:'Подтверждённой гарантии стипендии нет.'},
 {id:'wut-cs',title:'Computer Science',school:'Warsaw University of Technology',country:'Польша',interest:'Технологии',duration:'8 семестров',accent:'plum',programUrl:'https://www.students.pw.edu.pl/Studies-Offer/B.Sc.-offer',admissionUrl:'https://www.students.pw.edu.pl/How-to-Apply/Admission-to-B.Sc',checkedOn,tuition:{amount:5520,currency:'EUR',period:'semester',year:'2026/27',source:'https://www.students.pw.edu.pl/Studies-Offer/B.Sc.-offer',note:'Тариф non-EU; 2027/28 ещё не подтверждён.'},english:{ielts:6,detail:'IELTS Academic 6.0 указан в правилах; альтернативы проверяй на сайте.',source:'https://www.students.pw.edu.pl/Resources/Application-Glossary/English-Proficiency'},deadline:null,admissionNote:'Для казахстанского аттестата проверь признание NAWA и актуальный календарь 2027/28.',specialRequirement:'Для ряда иностранных документов требуется онлайн-собеседование и признание аттестата NAWA.',scholarshipNote:'Наличие стипендии для этого маршрута не подтверждено.'},
 {id:'kozminski-management',title:'Bachelor in Management',school:'Kozminski University',country:'Польша',interest:'Бизнес',duration:'3 года',accent:'sage',programUrl:'https://www.kozminski.edu.pl/en/programs/undergraduate-programs-bachelor/bachelor-management',admissionUrl:'https://www.kozminski.edu.pl/en/programs/undergraduate-programs-bachelor/bachelor-management',checkedOn,tuition:{amount:19400,currency:'PLN',period:'semester',year:'2026/27',source:'https://www.kozminski.edu.pl/en/programs/undergraduate-programs-bachelor/bachelor-management',note:'Первый год; на втором и третьем цена выше. Admission fee: 85 PLN.'},english:{ielts:6.5,detail:'IELTS Academic 6.5; университет принимает и другие способы подтверждения.',source:'https://www.kozminski.edu.pl/en/programs/undergraduate-programs-bachelor/bachelor-management'},deadline:null,admissionNote:'Для документов из Казахстана университет указывает дополнительный online knowledge test.',specialRequirement:'Дополнительный тест знаний для ряда стран, включая Казахстан.',scholarshipNote:'На сайте есть конкурсы стипендий; условия и сроки конкретного набора проверяй отдельно.'},
 {id:'pjait-graphic',title:'Graphic Design and Multimedia Art — New Media Art',school:'Polish-Japanese Academy of Information Technology',country:'Польша',interest:'Дизайн',duration:'3 года',accent:'sand',programUrl:'https://pja.edu.pl/en/projektowanie-graficzne-i-sztuka-multimediow/projektowanie-graficzne-i-sztuka-multimediow-studia-i-stopnia-stacjonarne-anglojezyczne/o-kierunku/',admissionUrl:'https://pja.edu.pl/en/projektowanie-graficzne-i-sztuka-multimediow/projektowanie-graficzne-i-sztuka-multimediow-studia-i-stopnia-stacjonarne-anglojezyczne/o-kierunku/',checkedOn,tuition:{amount:2400,currency:'PLN',period:'month',year:'текущая страница, с 2024/25',source:'https://pja.edu.pl/en/projektowanie-graficzne-i-sztuka-multimediow/oplaty-za-studia/projektowanie-graficzne-i-sztuka-multimediow-studia-i-stopnia-stacjonarne-anglojezyczne/',note:'10 платежей в первый год (24 000 PLN/год); qualification fee 150 PLN.'},english:{ielts:null,detail:'Англоязычный поток; числовой порог IELTS не подтверждён.',source:'https://pja.edu.pl/en/projektowanie-graficzne-i-sztuka-multimediow/projektowanie-graficzne-i-sztuka-multimediow-studia-i-stopnia-stacjonarne-anglojezyczne/o-kierunku/'},deadline:null,admissionNote:'Уточни правила признания аттестата и сроки нового набора.',specialRequirement:'Портфолио и квалификационное интервью.',scholarshipNote:'Стипендия для этой программы и граждан Казахстана не подтверждена.'},
 {id:'twente-tcs',title:'Technical Computer Science',school:'University of Twente',country:'Нидерланды',interest:'Технологии',duration:'3 года',accent:'plum',programUrl:'https://www.utwente.nl/en/education/bachelor/programmes/technical-computer-science/',admissionUrl:twenteAdmission,checkedOn,tuition:{amount:16869,currency:'EUR',period:'year',year:'2027/28',source:twenteFees,note:'Тариф non-EU/EEA; application fee и проживание отдельно.'},english:{ielts:6,detail:'IELTS Academic overall 6.0 и минимум 5.5 в каждом компоненте.',source:twenteEnglish},deadline:{date:'2027-05-01',label:'Non-EU, требуется виза',intake:'2027',source:'https://www.utwente.nl/en/education/bachelor/programmes/technical-computer-science/'},admissionNote:twenteDiploma,specialRequirement:'Математика Advanced/Higher Level; возможна индивидуальная проверка профильных предметов.',scholarshipNote:'Наличие подходящей бакалаврской стипендии нужно проверять отдельно.'},
 {id:'twente-iba',title:'International Business Administration',school:'University of Twente',country:'Нидерланды',interest:'Бизнес',duration:'3 года',accent:'sage',programUrl:'https://www.utwente.nl/en/education/bachelor/programmes/international-business-administration/',admissionUrl:twenteAdmission,checkedOn,tuition:{amount:12652,currency:'EUR',period:'year',year:'2027/28',source:twenteFees,note:'Тариф non-EU/EEA; application fee и проживание отдельно.'},english:{ielts:6,detail:'IELTS Academic overall 6.0 и минимум 5.5 в каждом компоненте.',source:twenteEnglish},deadline:null,admissionNote:twenteDiploma,scholarshipNote:'Наличие подходящей бакалаврской стипендии нужно проверять отдельно.'},
 {id:'twente-ide',title:'Industrial Design Engineering',school:'University of Twente',country:'Нидерланды',interest:'Дизайн',duration:'3 года',accent:'sand',programUrl:'https://www.utwente.nl/en/education/bachelor/programmes/industrial-design-engineering/',admissionUrl:twenteAdmission,checkedOn,tuition:{amount:16869,currency:'EUR',period:'year',year:'2027/28',source:twenteFees,note:'Тариф non-EU/EEA; application fee и проживание отдельно.'},english:{ielts:6,detail:'IELTS Academic overall 6.0 и минимум 5.5 в каждом компоненте.',source:twenteEnglish},deadline:null,admissionNote:twenteDiploma,specialRequirement:'Профильную математику нужно сверить с требованиями программы.',scholarshipNote:'Наличие подходящей бакалаврской стипендии нужно проверять отдельно.'},
 {id:'asu-cs',coverImage:'/universities/asu.jpg',title:'Computer Science, BS',school:'Arizona State University',country:'США',interest:'Технологии',duration:'4 года',accent:'plum',programUrl:'https://degrees.asu.edu/bachelors/major/ASU00/ESCSEBS/computer-science',admissionUrl:'https://admission.asu.edu/apply/international/first-year',checkedOn,tuition:{amount:39062,currency:'USD',period:'year',year:'2026/27',source:'https://admission.asu.edu/cost-aid/international',note:'Базовая tuition; обязательные университетские fees, страховка и проживание сверху.'},english:{ielts:6.5,detail:'Для Fulton Schools of Engineering IELTS 6.5.',source:'https://admission.asu.edu/apply/international/first-year'},deadline:null,admissionNote:'Дополнительные требования инженерной школы выше общих требований ASU; SAT/ACT не единственный путь.',scholarshipNote:'Merit scholarship NAMU доступна ограниченному числу иностранных бакалавров; сумма не гарантирована.'},
 {id:'babson-bsba',title:'Bachelor of Science in Business Administration',school:'Babson College',country:'США',interest:'Бизнес',duration:'4 года',accent:'sage',programUrl:'https://undergraduatecatalog.babson.edu/bsba/bachelor-of-science-in-business-administration',admissionUrl:'https://www.babson.edu/undergraduate/admission/',checkedOn,tuition:{amount:60288,currency:'USD',period:'year',year:'2026/27',source:'https://www.babson.edu/undergraduate/tuition-and-financial-aid/tuition-and-expenses/',note:'Tuition; жильё, питание, страховка и прочие расходы отдельно.'},english:{ielts:null,detail:'Нужен официальный способ подтверждения английского; универсальный числовой минимум не подтверждён.',source:'https://www.babson.edu/undergraduate/admission/'},deadline:null,admissionNote:'Проверь актуальные требования к школьным документам, эссе и рекомендациям.',scholarshipNote:'Финансовую помощь проверяй по отдельным условиям для international applicants.'},
 {id:'parsons-design',title:'Communication Design, BFA',school:'Parsons School of Design',country:'США',interest:'Дизайн',duration:'4 года',accent:'sand',programUrl:'https://www.newschool.edu/parsons/bfa-communication-design/',admissionUrl:'https://www.newschool.edu/parsons/how-to-apply-undergraduate/',checkedOn,tuition:{amount:31174,currency:'USD',period:'semester',year:'2026/27',source:'https://ww4.newschool.edu/tuition-fees-billing/new-students-tuition/',note:'Full-time tuition; университетские fees и проживание отдельно.'},english:{ielts:null,detail:'Подтверждение английского зависит от условий для international applicants; IELTS-порог не подтверждён.',source:'https://www.newschool.edu/parsons/how-to-apply-undergraduate/'},deadline:null,admissionNote:'Подача через Common Application и Admission Hub.',specialRequirement:'Портфолио 8–12 слайдов обязательно; интервью не требуется.',scholarshipNote:'Портфолио учитывается при рассмотрении на финансирование.'},
 {id:'pavia-ai',title:'Artificial Intelligence',school:'University of Pavia',country:'Италия',interest:'Технологии',duration:'3 года',accent:'plum',programUrl:'https://en.unipv.it/en/education/bachelors-and-masters-degree-programs/first-cycle-degree-course/artificial-intelligence',admissionUrl:'https://en.unipv.it/en/education/bachelors-and-masters-degree-programs/first-cycle-degree-course/artificial-intelligence',checkedOn,tuition:null,english:{ielts:null,detail:'Программа на английском; подтверждённый порог IELTS для нового набора не найден.',source:'https://en.unipv.it/en/education/bachelors-and-masters-degree-programs/first-cycle-degree-course/artificial-intelligence'},deadline:null,admissionNote:'Ограниченный набор. Правила и квоты для non-EU, проживающих за пределами Италии, отличаются; календарь 2027/28 не опубликован.',specialRequirement:'В правилах 2026/27 есть вступительный тест CEnT-S или English TOLC-I; требования 2027/28 нужно обновить.',scholarshipNote:'Условия финансирования для этой программы нужно проверить отдельно.'},
 {id:'bocconi-management',title:'Management',school:'Bocconi University',country:'Италия',interest:'Бизнес',duration:'3 года',accent:'sage',programUrl:'https://www.unibocconi.it/en/programs/bachelor-science/management',admissionUrl:'https://www.unibocconi.it/en/applying-bocconi/bachelor-and-law-programs/application-and-admissions/admissions',checkedOn,tuition:{amount:17000,currency:'EUR',period:'year',year:'2026/27',source:'https://www.unibocconi.it/en/applying-bocconi/bachelor-and-law-programs/fees',note:'Тариф 2027/28 ещё не опубликован; 2026/27 дан только как ориентир.'},english:{ielts:null,detail:'Программа на английском; конкретный порог IELTS для приёма не подтверждён.',source:'https://www.unibocconi.it/en/programs/bachelor-science/management'},deadline:{date:'2027-01-26',label:'Winter Session, международные абитуриенты',intake:'2027',source:'https://www.unibocconi.it/en/applying-bocconi/bachelor-and-law-programs/application-and-admissions/admissions'},admissionNote:'Нужен один из тестов: Bocconi Online Test, SAT или ACT. Есть более ранняя Early Session.',scholarshipNote:'Есть Bocconi4Access и частичное освобождение от tuition; условия отдельной заявки.'},
 {id:'naba-design',title:'Design, BA',school:'NABA',country:'Италия',interest:'Дизайн',duration:'3 года',accent:'sand',programUrl:'https://www.naba.it/en/undergraduate/design',admissionUrl:'https://www.naba.it/en/undergraduate-counseling/tuition-fee-scholarships-financial-aid',checkedOn,tuition:{amount:22250,currency:'EUR',period:'year',year:'2026/27',source:'https://www.naba.it/en/faq/tuition-fees-and-scholarships/naba-tuition-fees',note:'Тариф non-EU для кампуса в Италии; будущий набор может отличаться.'},english:{ielts:null,detail:'Англоязычный трек есть; актуальный допустимый сертификат и минимум проверяй у NABA.',source:'https://www.naba.it/en/undergraduate/design'},deadline:null,admissionNote:'Выбери кампус и английский трек при заявке; требования к диплому уточни у NABA.',specialRequirement:'Для стипендиальных конкурсов обычно требуется творческое портфолио.',scholarshipNote:'Проводятся конкурсы стипендий; дедлайн стипендии не равен общему дедлайну приёма.'},
 {id:'suny-cs',title:'Computer Science, BS',school:'SUNY Korea / Stony Brook University',country:'Южная Корея',interest:'Технологии',duration:'4 года',accent:'plum',programUrl:'https://cs.sunykorea.ac.kr/cs/html/sub01/0103.html',admissionUrl:'https://ts.sunykorea.ac.kr/adm/html/sub02/02010103.html',checkedOn,tuition:{amount:11775,currency:'USD',period:'semester',year:'осень 2026',source:'https://www.sunykorea.ac.kr/costaid/',note:'Тариф Non-NYS Resident; fees, проживание и обучение на кампусе Stony Brook в США отдельно.'},english:{ielts:6.5,detail:'IELTS 6.5 либо один из других признанных тестов.',source:'https://ts.sunykorea.ac.kr/adm/html/sub02/02010103.html'},deadline:{date:'2027-06-24',label:'Final deadline Fall 2027; для визы советуют подать до 18 марта',intake:'2027',source:'https://www.sunykorea.ac.kr/adm/html/sub02/02030101.html'},admissionNote:'Программа предусматривает период обучения в США; общий бюджет обучения может быть выше.',scholarshipNote:'Ранняя подача даёт приоритет при рассмотрении на стипендию.'},
 {id:'yonsei-ctm',title:'Creative Technology Management (UIC major)',school:'Yonsei University, Underwood International College',country:'Южная Корея',interest:'Бизнес',duration:'4 года',accent:'sage',programUrl:'https://uic.yonsei.ac.kr/undergraduate.php?mid=m02_02_04',admissionUrl:yonseiAdmission,checkedOn,tuition:{amount:8202000,currency:'KRW',period:'semester',year:'2026',source:yonseiFees,note:'Обычный семестр International Students Track; первый семестр дороже, fees отдельно.'},english:{ielts:null,detail:'С набора 2027 доказательство английского обязательно, но минимальный IELTS не установлен.',source:yonseiAdmission},deadline:null,admissionNote:'Это major внутри UIC/HASS, а не самостоятельная заявка на отдельный бакалавриат. Маршрут поступления проверь в UIC.',scholarshipNote:'Международных абитуриентов UIC автоматически рассматривают на вступительную стипендию.'},
 {id:'yonsei-iid',title:'Information and Interaction Design (UIC major)',school:'Yonsei University, Underwood International College',country:'Южная Корея',interest:'Дизайн',duration:'4 года',accent:'sand',programUrl:'https://uic.yonsei.ac.kr/undergraduate.php?mid=m02_02_03',admissionUrl:yonseiAdmission,checkedOn,tuition:{amount:8202000,currency:'KRW',period:'semester',year:'2026',source:yonseiFees,note:'Обычный семестр International Students Track; первый семестр дороже, fees отдельно.'},english:{ielts:null,detail:'С набора 2027 доказательство английского обязательно, но минимальный IELTS не установлен.',source:yonseiAdmission},deadline:null,admissionNote:'Это major внутри UIC/HASS, а не самостоятельная заявка на отдельный бакалавриат. Маршрут поступления проверь в UIC.',scholarshipNote:'Международных абитуриентов UIC автоматически рассматривают на вступительную стипендию.'},
 {id:'nu-cs',coverImage:'/universities/nu.jpg',title:'Computer Science',school:'Nazarbayev University',country:'Казахстан',interest:'Технологии',duration:'4 года',accent:'plum',programUrl:'https://nu.edu.kz/sprogram/bachelor-of-science-in-computer-science/',admissionUrl:'https://nu.edu.kz/admissions/how-to-apply/foundation-undergraduate/regular-admissions/',checkedOn,tuition:{amount:15000,currency:'USD',period:'year',year:'2026/27',source:'https://nu.edu.kz/admissions/how-to-apply/foundation-undergraduate/regular-admissions/',note:'Для местных и иностранных студентов; возможны гранты.'},english:{ielts:6,detail:'Для Regular Admission: IELTS overall 6.0, Writing 6.0, остальные компоненты минимум 5.5.',source:'https://nu.edu.kz/admissions/how-to-apply/foundation-undergraduate/regular-admissions/'},deadline:null,admissionNote:'Есть несколько путей отбора: NUET, SAT/ACT и другие квалификации. На странице программы заголовок BSc, описание B.Eng.; степень нужно уточнить у вуза.',scholarshipNote:'Финансовая поддержка и гранты рассматриваются по отдельным правилам.'},
 {id:'sdu-cs',coverImage:'/universities/sdu.jpg',title:'Computer Science',school:'SDU University',country:'Казахстан',interest:'Технологии',duration:'4 года',accent:'sage',programUrl:'https://sdu.edu.kz/en/computer-science-3/',admissionUrl:'https://sdu.edu.kz/en/admission-3-2/',checkedOn,tuition:{amount:33000,currency:'KZT',period:'credit',year:'2026/27',source:'https://drive.google.com/file/d/1lK2lTI3pyZkNQ1q9n_9-Jpg0CiLpJZO4/preview',annualRange:{min:1140000,max:1980000,credits:60},note:'Для граждан Казахстана: 33 000 ₸/ECTS по профильным предметам и 19 000 ₸/ECTS по общеобразовательным. Диапазон рассчитан для 60 ECTS в год; фактическая сумма зависит от учебного плана. Разовый студенческий взнос — 60 000 ₸, проживание отдельно. Для иностранных студентов в тарифе указаны цены в USD.'},english:{ielts:5.5,detail:'IELTS overall 5.5 и минимум 5.0 в каждом компоненте; также принимаются сертификат языковой школы SDU уровня B1 или внутренний экзамен.',source:'https://sdu.edu.kz/en/admission-3-2/'},deadline:null,admissionNote:'Программа 6B06102, Bachelor of Information and Communication Technologies. Для выпускников Казахстана приём основан на ЕНТ, профильные предметы — математика и информатика. На странице программы указан порог 50 для платного обучения; для набора 2027/28 проверь его заново.',specialRequirement:'Подготовь ЕНТ по математике и информатике; условия для иностранных документов уточни отдельно.',scholarshipNote:'Есть государственные гранты и конкурсные скидки SDU; на странице программы указан порог 120 для гранта, но это не гарантия финансирования.'},
 {id:'kimep-management',title:'Management (BMGT)',school:'KIMEP University',country:'Казахстан',interest:'Бизнес',duration:'4 года',accent:'sage',programUrl:'https://www.kimep.kz/bang-college-of-business/kz/bachelor-of-management/',admissionUrl:'https://www.kimep.kz/prospective-students/kz/admission/high-school-graduates/',checkedOn,tuition:{amount:163230,currency:'KZT',period:'credit',year:'2026/27',source:'https://www.kimep.kz/prospective-students/files/2026/05/Tuition-and-fees-eng-2026-27.pdf',note:'Цена за кредит; годовая сумма зависит от нагрузки. Обязательные сборы отдельно.'},english:{ielts:null,detail:'Уточни требование к английскому и доступные внутренние тесты.',source:'https://www.kimep.kz/prospective-students/kz/admission/high-school-graduates/'},deadline:null,admissionNote:'Для граждан Казахстана на странице приёма указан ЕНТ и профильные предметы география + математика.',specialRequirement:'Уточни порог ЕНТ для набора 2027/28.',scholarshipNote:'Стипендии и скидки проверяй по правилам конкретного года.'},
 {id:'aitu-media',title:'Media Technologies',school:'Astana IT University',country:'Казахстан',interest:'Дизайн',duration:'3 года',accent:'sand',programUrl:'https://astanait.edu.kz/mediatechbachelor',admissionUrl:'https://astanait.edu.kz/en/bachelor',checkedOn,tuition:{amount:2500000,currency:'KZT',period:'year',year:'2026/27',source:'https://astanait.edu.kz/en/bachelor',note:'Стоимость бакалавриата; 2027/28 ещё не опубликована.'},english:{ielts:null,detail:'Подтверждённый числовой порог IELTS не найден.',source:'https://astanait.edu.kz/mediatechbachelor'},deadline:null,admissionNote:'Программа 6B06105; профильные предметы — математика и информатика.',scholarshipNote:'На сайте перечислены гранты и скидки; право на них нужно проверять отдельно.'},
];

// Snapshot from the National Bank of Kazakhstan, 18 September 2026. For planning only.
export const fx = {date:'2026-09-18',source:'https://nationalbank.kz/ru/exchangerates/ezhednevnye-oficialnye-rynochnye-kursy-valyut',kztPerEur:510.29,kztPerUsd:444.58,kztPerPln:117.01,kztPerKrw:0.3212};
export function tuitionPerYear(program:Program): {amount:number;currency:Currency;referenceYear:string}|null {
 const t=program.tuition;if(!t || t.period==='credit')return null;
 return {amount:t.amount*(t.period==='semester'?2:t.period==='month'?10:1),currency:t.currency,referenceYear:t.year};
}
export function approximateEur(program:Program):number|null {
 const annual=tuitionPerYear(program);if(!annual)return null;
 const ratio:Partial<Record<Currency,number>>={EUR:1,USD:fx.kztPerUsd/fx.kztPerEur,PLN:fx.kztPerPln/fx.kztPerEur,KRW:fx.kztPerKrw/fx.kztPerEur,KZT:1/fx.kztPerEur};
 const rate=ratio[annual.currency];
 return rate===undefined?null:Math.round(annual.amount*rate);
}
export function annualRangeEur(program:Program):{min:number;max:number}|null {
 const tuition=program.tuition,range=tuition?.annualRange;
 if(!tuition||!range)return null;
 const ratio:Partial<Record<Currency,number>>={EUR:1,USD:fx.kztPerUsd/fx.kztPerEur,PLN:fx.kztPerPln/fx.kztPerEur,KRW:fx.kztPerKrw/fx.kztPerEur,KZT:1/fx.kztPerEur};
 const rate=ratio[tuition.currency];
 return rate===undefined?null:{min:Math.round(range.min*rate),max:Math.round(range.max*rate)};
}
