const campusPhotos: Record<string, string> = {
  'Imperial College London': '/universities/imperial.jpg',
  'London School of Economics (LSE)': '/universities/lse.jpg',
  'University College London (UCL)': '/universities/ucl.jpg',
  'University of Cambridge': '/universities/cambridge.jpg',
  'University of Edinburgh': '/universities/edinburgh.jpg',
  'University of Oxford': '/universities/oxford.jpg',
  'Berlin University of the Arts (UdK)': '/universities/udk.jpg',
  'Constructor University': '/universities/constructor.jpg',
  'Heidelberg University': '/universities/heidelberg.jpg',
  'LMU Munich': '/universities/lmu.jpg',
  'Rhine-Waal University of Applied Sciences': '/universities/rhine-waal.jpg',
  'Technical University of Munich (TUM)': '/universities/tum.jpg',
  'Bocconi University': '/universities/bocconi.jpg',
  'NABA': '/universities/naba.jpg',
  'NABA (Nuova Accademia di Belle Arti)': '/universities/naba.jpg',
  'Politecnico di Milano': '/universities/polimi.jpg',
  'Sapienza University of Rome': '/universities/sapienza.jpg',
  'University of Bologna': '/universities/bologna.jpg',
  'University of Pavia': '/universities/pavia.jpg',
  'Astana IT University': '/universities/aitu.jpg',
  'KIMEP University': '/universities/kimep.jpg',
  'Narxoz University': '/universities/narxoz.jpg',
  'Nazarbayev University': '/universities/nu.jpg',
  'SDU University': '/universities/sdu.jpg',
  'University of British Columbia (UBC)': '/universities/ubc.jpg',
  'University of Toronto': '/universities/toronto.jpg',
  'Delft University of Technology (TU Delft)': '/universities/delft.jpg',
  'Erasmus University Rotterdam': '/universities/erasmus.jpg',
  'Leiden University': '/universities/leiden.jpg',
  'University of Amsterdam (UvA)': '/universities/uva.jpg',
  'University of Twente': '/universities/twente.jpg',
  'Wageningen University & Research': '/universities/wageningen.jpg',
  'Jagiellonian University': '/universities/jagiellonian.jpg',
  'Kozminski University': '/universities/kozminski.jpg',
  'Polish-Japanese Academy of Information Technology': '/universities/pjatk.jpg',
  'University of Warsaw': '/universities/warsaw.jpg',
  'Warsaw University of Technology': '/universities/warsaw-tech.jpg',
  'Arizona State University': '/universities/asu.jpg',
  'Babson College': '/universities/babson.jpg',
  'Boston University': '/universities/boston.jpg',
  'New York University (NYU)': '/universities/nyu.jpg',
  'Parsons School of Design': '/universities/parsons.jpg',
  'University of California, Berkeley': '/universities/berkeley.jpg',
  'Sciences Po': '/universities/sciences-po.jpg',
  'École Polytechnique': '/universities/ecole-polytechnique.jpg',
  'Charles University': '/universities/charles.jpg',
  'Czech Technical University in Prague (CTU)': '/universities/ctu.jpg',
  'KAIST': '/universities/kaist.jpg',
  'Korea University': '/universities/korea.jpg',
  'SUNY Korea / Stony Brook University': '/universities/suny-korea.jpg',
  'Yonsei University, Underwood International College': '/universities/yonsei.jpg',
};

export function campusPhoto(university: string): string | undefined {
  return campusPhotos[university];
}
